### ISSUE TITLE
Print

### ISSUE THREAD

**Issue by DeepZono** [andbloch/eth-dl-cheat-sheet#1]
Hey i am just wondering how you printed your cheat sheet for the exam because when I used the standard ETH printer, the formulae are not so visible. The symbols especially are all blurred! Any tips?

**Comment by andbloch** [comment]
I just used the high quality settings (slow and precise printing) on my printer at home - that worked all fine. The ETH printers usually tend to print quickly and sacrifice the quality of detail. I'm not sure if you can increase the print quality on the ETH printers. Anyways, my rendered PDF seems to be fine. Also, make sure that you're allowed to bring a cheat sheet with this font size to the exam (we had no restrictions that year, I don't know how it's now).
